version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: res_pos_postgres
    restart: always
    environment:
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_pass
      POSTGRES_DB: pos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docs/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
